route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - chat_id: 
        bot_token: 
        send_resolved: true
        parse_mode: HTML
        message: "🔥 Alert: {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}"
