services:
  nginx-proxy:
    image: nginx:mainline-alpine
    container_name: nginx-proxy
    ports:
      # Порт HTTP
      - "80:80"
      # Порт HTTPS
      - "433:433"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  web-1:
    image: nginxdemos/hello:plain-text

  web-2:
    image: nginxdemos/hello:plain-text
