---
# tasks file for container-orchestrator
- name: create directory
  ansible.builtin.file:
    path: /tmp/compose/
    state: directory

- name: get Docker Compose file
  synchronize:
    src: /tmp/compose/
    dest: /tmp/compose/
    mode: push
    rsync_opts:
      - "--rsh='ssh'"
  delegate_to: serv1

- name: Start Docker containers
  become: true
  docker_compose:
    project_src: /tmp/compose/
    state: present
