{
 "title": "Summary",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "query_result(alertmanager_build_info)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(traefik_service_requests_total,service)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Нода ($node)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Использование CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование ОЗУ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ядер CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Загрузка SWAP",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Загрузка хранилища",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ОЗУ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Коды HTTP",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$service.*\",protocol=\"http\"}[$interval])) by (method, code)",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Наиболее востребованные сервисы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\r\n    label_replace(\r\n        sum by (service,code) \r\n          (rate(traefik_service_requests_total{service=~\"$service.*\",protocol=\"http\"}[$interval])) > 0,\r\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\r\n)",
     "legendFormat": "[{{code}}] на {{service}}"
    }
   ]
  },
  {
   "title": "Наиболее медленные сервисы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15,\r\n    label_replace(\r\n        traefik_service_request_duration_seconds_sum{service=~\"$service.*\",protocol=\"http\"} / \r\n          traefik_service_request_duration_seconds_count{service=~\"$service.*\",protocol=\"http\"},\r\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\r\n)\r\n\r\n",
     "legendFormat": "{{method}}[{{code}}] на {{service}}"
    }
   ]
  },
  {
   "title": "Менеджер предупреждений ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "datasource"
  },
  {
   "title": "Использование CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число активных alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число suppressed alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число активных silences",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}