apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  WHOAMI_NAME: {{ .Values.app.name }}
  WHOAMI_PORT_NUMBER: "{{ .Values.service.port }}"
