{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.app.name }}-ingress
    app: {{ .Values.app.name }}
spec:
  rules:
  - host: {{ .Values.ingress.hosts.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.hosts.paths.path }}
        {{- with .Values.ingress.hosts.paths.pathType }}
        pathType: {{ . }}
        {{- end }}
        backend:
          service:
            name: {{ .Values.app.name }}-service
            port: 
              number: {{ $.Values.service.port }}
{{- end }}
