groups:
- name: targets
  rules:
  - alert: monitor_service_down
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: 'Service {{ $labels.instance }} is down'

- name: hosts
  rules:
    - alert: high_cpu_load
      expr: avg(rate(node_cpu_seconds_total{mode!="idle"}[5m])) > 0.8
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: 'High CPU usage on {{ $labels.instance }} ({{ $value | printf "%.0f" }}%)'
        
    - alert: peak_cpu_load
      expr: avg(rate(node_cpu_seconds_total{mode!="idle"}[1m])) > 0.95
      for: 3m
      labels:
        service: hardware
        severity: critical
      annotations:
        summary: 'Peak CPU usage on {{ $labels.instance }} ({{ $value | printf "%.0f" }}%)'
 
    - alert: null_cpu_load
      expr: avg(rate(node_cpu_seconds_total{mode="idle"}[10m])) > 0.90
      for: 3m
      labels:
        service: hardware
        severity: critical
      annotations:
        summary: 'CPU on {{ $labels.instance }} is not used'

    - alert: high_memory_load
      expr: 100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes) > 90
      for: 3m
      labels:
        service: hardware
        severity: warning
      annotations:
        summary: 'High memory utilization on {{ $labels.instance }} ({{ $value | printf "%.0f" }}%)'
 
    - alert: high_storage_load
      expr: (node_filesystem_free_bytes / node_filesystem_size_bytes) < 0.15
      for: 3m
      labels:
        service: hardware
        severity: error
      annotations:
        summary: 'Memory is almost full on {{ $labels.instance }} ({{ $value | printf "%.0f" }}%)'
        description: 'Dev {{ $labels.device }} mounted on {{ $labels.mountpoint }}: {{ $value | printf "%.2f" }}%.'
 
- name: containers
  rules:
    - alert: ContainerIsDown
      expr: (time() - container_last_seen) > 30
      for: 20s
      labels:
        service: container
        severity: error
      annotations:
        summary: 'Container {{ $labels.name }} is down'
        description: '{{ $labels.name }} Last seen on {{ $labels.instance }} {{ $value | printf "%.0f" }} seconds ago'
