---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Секреты хранятся в base64 (echo -n '' | base 64)
  mongo-root-username: dXNlcg==     # user
  mongo-root-password: cGFzc3dvcmQ= # password
