services:
  control:
    build: 
      context: .
      dockerfile: control.Dockerfile
    volumes:
      - ./volume-ansible/:/etc/ansible/
    tty: true

  serv1:
    build: 
      context: .
      dockerfile: managed.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  serv2:
    build: 
      context: .
      dockerfile: managed.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
